### ISSUE TITLE
wrong order for latitude?

### ISSUE THREAD

**Issue by yiliouc** [trondkr/ERA5-ROMS#6]
Hi Trond, 

Thanks for this great piece of code, but I came into some issue that ROMS model (I'm using COAWST actually) can't read the forcing data. It seems ROMS doesn't like the latitude to be from 90 to -90, I modified "ECMWF_convert_to_ROMS.py" with following:

    vnc = f1.createVariable('lat', 'd', 'lat', fill_value=fill_val)
    vnc.long_name = 'Latitude'
    vnc.units = 'degree_north'
    vnc.standard_name = 'latitude'
    vnc[:] = latitude[::-1]

    vnc = f1.createVariable(metadata['roms_name'], 'd', (metadata['time_name'], 'lat', 'lon'), fill_value=fill_val)
    vnc.long_name = metadata["name"]
    vnc.standard_name = metadata["short_name"]
    vnc.coordinates = "lon lat {}".format(metadata['time_name'])
    vnc.units = var_units
    vnc.missing_value = fill_val
    vnc[:, :, :] = data_array[:,::-1,:]

and ROMS is running. Not sure if it's an error with ROMS or COAWST, but I think it may be worth bringing it to you.

Cheers,
Yi

**Comment by trondkr** [comment]
Hi Yi,

Thank you for reporting this back to me. I have been having some issues I was unable to resolve lately and this may be the reason for why. Would you mind putting in a pull request so that I can make sure we are working on the same code? I would appreciate having your fix included here. Thanks.

Cheers, Trond
